spring.application.name=HewanKu
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:41632/railway
spring.datasource.username=root
spring.datasource.password=HUWsObmyZEKbSVScDSqWvXtFoNeGObAX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true